// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { HorizontalBox, VerticalBox, ListView, StandardListView, CheckBox } from "std-widgets.slint";

export struct EventDesc {
    name: string,
    minors: [string]
}

export global EnablesData {
    in property <[EventDesc]> event_descs;
    callback toggled_major(int, bool);
    callback toggled_minor(int, int, bool);
}

export component EventsEnables inherits VerticalBox {
    spacing: 2rem;
    width: 25rem;

    Text {
        text: @tr("events enables");
        font-size: 1.5rem;
        horizontal-alignment: left;
    }
    ListView {
        for major[index_major] in EnablesData.event_descs: HorizontalBox {
            major_cb := CheckBox {
                text: major.name;
                toggled => {EnablesData.toggled_major(index_major, self.checked)}
            }
            VerticalBox {
                for minor[index_minor] in major.minors : HorizontalBox {
                    minor_cb := CheckBox {
                        text: minor;
                        toggled => {
                            if (self.checked) {major_cb.checked = true}
                            EnablesData.toggled_minor(index_major, index_minor, self.checked)
                        }
                    }
                }
            }
        }
    }
}
