// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import {StandardTableView, VerticalBox, TabWidget, ScrollView, HorizontalBox, ListView, Palette, Button, LineEdit} from "std-widgets.slint";
import {TableView} from "table_view.slint";
import { TextCopiable } from "text_copiable.slint";
import { FindBar } from "find_bar.slint";


export struct StackWalkInfo {
    event_timestamp: string,
    process_id: string,
    thread_id: string,
    stacks: [string]
}

export global EventsViewData  {
    in property <[TableColumn]> column_names;
    in property <[[StandardListViewItem]]> row_data: [];
    callback sort_ascending(int);
    callback sort_descending(int);
    callback row-data-detail(/* row-index */ int) -> string;
    callback stack-walk(/* row-index */ int) -> StackWalkInfo;
    callback row-find(string) -> {result: bool, indexes: [int], error: string};
}

export component EventsView inherits VerticalBox {
    private property <string> row-data-detail-info;
    private property <StackWalkInfo> stacks-info;

    spacing: 2px;
    padding: 0px;
    
    HorizontalBox {
        padding: 0px;
        alignment: end;

        FindBar {
            placeholder-text: "process_id = 1 && properties.xxx = 1 || xxx";
    
            row-find(filter_expr) => {
                return EventsViewData.row-find(filter_expr);
            }
            set-current-row(index) => {
                table_view.set-current-row(index)
            }
        }
    }

    table_view := TableView {
        sort-ascending(index) => {
            EventsViewData.sort_ascending(index);
        }
        sort-descending(index) => {
            EventsViewData.sort-descending(index);
        }

        columns: EventsViewData.column_names;
        rows: EventsViewData.row_data;

        row-double-clicked(index-row) => {
            root.row-data-detail-info = EventsViewData.row-data-detail(index-row);
            root.stacks-info = EventsViewData.stack-walk(index-row);
            popup.show();
        }
    }
    HorizontalBox {
        height: text.height;
        padding-left: 12px;
        padding-right: 12px;

        text := TextCopiable {
            height: self.font-size + 2px;
            text: @tr("total: {}", EventsViewData.row_data.length);
            font-weight: 500;
            font-size: 1.2rem;
        }
    }

    popup := PopupWindow {
        private property <length> font-size: 1.2rem;
        x: table_view.order-column-width + 15px;
        y: table_view.y + table_view.header-height + 12px;
        width: root.width * 50%;
        height: root.height * 60%;
        min-width: font-size * 20;
        min-height: font-size * 30;
        close-on-click: false;

        Rectangle {
            clip: true;
            background: Palette.background;
            border-color: Palette.border;
            border-width: 1phx;

            VerticalBox {
                HorizontalBox {
                    preferred-height: 1.2rem;
                    alignment: end;
                    Button {
                        text: "close";
                        clicked => {
                            popup.close();
                        }
                    }
                }
                tabs := TabWidget {
                    Tab {
                        title: "event detail";

                        sv := ScrollView {
                            x: 0;
                            y: 0;
                            viewport-width: rect.preferred-width;
                            viewport-height: rect.preferred-height;

                            rect := Rectangle {
                                x: sv.viewport-x;
                                y: sv.viewport-y;
                                background: Palette.background;
                                
                                HorizontalBox {
                                    padding: 12px;
                                    TextCopiable {
                                        width: 100%;
                                        height: 100%;
                                        max-width: 100rem;
                                        horizontal-alignment: left;
                                        vertical-alignment: top;
                                        wrap: word-wrap;
                                        text: root.row-data-detail-info;
                                        font-weight: 500;
                                        font-size: 1.2rem;
                                    }
                                }
                            }
                        }
                    }
                    Tab {
                        title: "stacks";

                        VerticalBox {
                            HorizontalBox {
                                padding-left: 12px;
                                padding-right: 12px;
                                padding-top: 9px;
                                padding-bottom: 9px;

                                TextCopiable {
                                    text: @tr("process id: {}", root.stacks-info.process-id);
                                    font-weight: 500;
                                    font-size: 1.2rem;
                                }
            
                                TextCopiable {
                                    text: @tr("thread id: {}", root.stacks-info.thread-id);
                                    font-weight: 500;
                                    font-size: 1.2rem;
                                }

                                TextCopiable {
                                    text: @tr("event timestamp: {}", root.stacks-info.event-timestamp);
                                    font-weight: 500;
                                    font-size: 1.2rem;
                                }
                            }
                            ListView {
                                for item in root.stacks-info.stacks: Rectangle {
                                    HorizontalLayout {
                                        padding-left: 12px;
                                        padding-right: 12px;
                                        padding-top: 9px;
                                        padding-bottom: 9px;
                                
                                        main-text := TextCopiable {
                                            width: 100%;
                                            height: 100%;
                                            horizontal-alignment: left;
                                            vertical-alignment: center;
                                            text: item;
                                            font-weight: 500;
                                            font-size: 1.2rem;
                                            single-line: true;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
           }
        }
    }
}
