// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import {StandardTableView, VerticalBox} from "std-widgets.slint";
import {TableView} from "table_view.slint";

export global EventsViewData  {
    callback sort_ascending(int);
    callback sort_descending(int);
    in property <[[StandardListViewItem]]> row_data: [];
}

export component EventsView inherits VerticalBox {
    spacing: 2rem;
    
    Text {
        text: @tr("events view");
        font-size: 1.5rem;
        horizontal-alignment: left;
    }
    TableView {
        sort-ascending(index) => {
            EventsViewData.sort_ascending(index);
        }
        sort-descending(index) => {
            EventsViewData.sort-descending(index);
        }

        columns: [
            {title: @tr("datetime"), width: 18rem},
            {title: @tr("process_id"), width: 9rem},
            {title: @tr("thread_id"), width: 9rem},
            {title: @tr("event_name"), width: 12rem},
            {title: @tr("opcode_name"), width: 10rem},
            {title: @tr("properties"), width: 50rem},
        ];
        rows: EventsViewData.row_data;
    }
}
