// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import {StandardTableView, GroupBox} from "std-widgets.slint";

export global EventsViewData  {
    callback sort_ascending(int);
    callback sort_descending(int);
    in property <[[StandardListViewItem]]> row_data: [];
}

export component EventsView inherits GroupBox {
    title: @tr("events view");
    vertical-stretch: 0;

    StandardTableView {
        sort-ascending(index) => {
            EventsViewData.sort_ascending(index);
        }

        sort-descending(index) => {
            EventsViewData.sort-descending(index);
        }

        columns: [
            { title: @tr("Header 1") },
            { title: @tr("Header 2") },
            { title: @tr("Header 3") },
            { title: @tr("Header 4") },
        ];
        rows: EventsViewData.row_data;
    }
}
