import { HorizontalBox, LineEdit, Palette } from "std-widgets.slint";


export component FilterInput {
    in property <string> placeholder-text;
    callback set_filter_expression(string) -> {result: bool, message: string};
    
    HorizontalBox {
        padding: 0px;
        height: 7mm;

        private property <{result: bool, message: string}> result;

        LineEdit {
            placeholder-text: placeholder-text;

            accepted(text) => {
                result = set_filter_expression(text);
                popup.show();
            }
        }
        popup := PopupWindow {
            y: parent.preferred-height + 1mm;

            Rectangle {
                border-color: Palette.border;
                border-width: 1px;
                background: Palette.background;
                HorizontalBox {
                    Text {
                        text: result.result ? "update sucess!" : result.message;
                        color: result.result ? #90ee90 : #ec5353;
                    }
                }
            }
        }
    }
}