import { CheckBox, StandardListView, StyleMetrics , VerticalBox, HorizontalBox, LineEdit, Switch } from "std-widgets.slint";
import { EventsEnables, EnablesData, EventDesc, Enables } from "events_enable.slint";
import { EventsView, EventsViewData } from "events_view.slint";

export { EventsEnables, EnablesData, EventDesc, Enables, EventsViewData }

export component App inherits Window {
    preferred-width: 1000px;
    preferred-height: 600px;
    title: @tr("kernel events trace");
    icon: @image-url("./logo/slint-logo-small-light.png");

    callback start();
    callback stop();

    VerticalBox{
        HorizontalBox {
            Switch {
                text: @tr("On/Off");
                checked: false;
                toggled => {
                    if (self.checked) {
                        start()
                    } else {
                        stop()
                    }
                }
            }
            LineEdit {
                height: 2rem;
            }
        }
        HorizontalBox {
            EventsEnables{}
            Rectangle {background: gray; width: 2px;}
            EventsView{}
        }
    }
}